// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATAY6JXfx9wIX7uLseCv8NmBqXnkZGrys',
    appId: '1:928971158121:web:5ba58eba3b424b41e568f8',
    messagingSenderId: '928971158121',
    projectId: 'technocellagendamento',
    authDomain: 'technocellagendamento.firebaseapp.com',
    storageBucket: 'technocellagendamento.appspot.com',
    measurementId: 'G-5XZJ2LEQT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmLzFYk8Qa-Im6OlWg_8E3HRkKxZXnJA',
    appId: '1:928971158121:android:25d0a6286a8bbd66e568f8',
    messagingSenderId: '928971158121',
    projectId: 'technocellagendamento',
    storageBucket: 'technocellagendamento.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWR8GlBfoTrZphgbaFarCnr_NIoOIxvms',
    appId: '1:928971158121:ios:b68334aa662b733ce568f8',
    messagingSenderId: '928971158121',
    projectId: 'technocellagendamento',
    storageBucket: 'technocellagendamento.appspot.com',
    iosBundleId: 'com.example.appdouglas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWR8GlBfoTrZphgbaFarCnr_NIoOIxvms',
    appId: '1:928971158121:ios:c003cb8157f75028e568f8',
    messagingSenderId: '928971158121',
    projectId: 'technocellagendamento',
    storageBucket: 'technocellagendamento.appspot.com',
    iosBundleId: 'com.example.appdouglas.RunnerTests',
  );
}
